OMNeT++ Simulation Library: cLongHistogram Class Reference
cLongHistogram Class Reference
[Statistical data collection]
#include <chistogram.h>
Detailed Description
Equidistant histogram for integers.
This class is just a cHistogram preconfigured for collecting integers (MODE_INTEGERS).
Public Member Functions
Constructors, destructor, assignment.
cLongHistogram (const cLongHistogram &r)
cLongHistogram (const char *name=NULL, int numcells=-1)
virtual ~cLongHistogram ()
cLongHistogram & operator= (const cLongHistogram &other)
Redefined cObject member functions.
virtual cLongHistogram * dup () const
Redefined member functions from cStatistic and its subclasses.
virtual void collect (double value)
virtual void collect (SimTime value)
Constructor & Destructor Documentation
cLongHistogram::cLongHistogram (const cLongHistogram & r) [inline]
Copy constructor.
cLongHistogram::cLongHistogram (const char * name = NULL, int numcells = -1) [inline, explicit]
Constructor.
virtual cLongHistogram::~cLongHistogram () [inline, virtual]
Destructor.
Member Function Documentation
cLongHistogram& cLongHistogram::operator= (const cLongHistogram & other)
Assignment operator.
virtual cLongHistogram* cLongHistogram::dup () const [inline, virtual]
Creates and returns an exact copy of this object.
See cObject for more details.
Reimplemented from cStdDev.
virtual void cLongHistogram::collect (double value) [inline, virtual]
Collects one value.
Internally, the double value is converted to an integer using floor() before any processing.
Reimplemented from cDensityEstBase.
References cDensityEstBase::collect().
virtual void cLongHistogram::collect (SimTime value) [inline, virtual]
Convenience method, delegates to collect(double).
Reimplemented from cDensityEstBase.
References cDensityEstBase::collect(), and SimTime::dbl().
The documentation for this class was generated from the following file:
chistogram.h