OMNeT++ Simulation Library: opp_string Class Reference
opp_string Class Reference
[Internal classes]
#include <opp_string.h>
Detailed Description
Lightweight string class, used internally in some parts of OMNeT++.
In simulation models it is better to use std::string or const char * instead.
opp_string has only one data member, a char* pointer. Allocation and deallocation of the contents takes place via opp_strdup() and operator delete.
Public Member Functions
opp_string ()
opp_string (const char *s)
opp_string (const char *s, int n)
opp_string (const std::string &s)
opp_string (const opp_string &s)
~opp_string ()
const char * c_str () const
bool empty () const
char * buffer ()
char * reserve (unsigned size)
const char * operator= (const char *s)
opp_string & operator= (const opp_string &s)
opp_string & operator= (const std::string &s)
bool operator< (const opp_string &s) const
opp_string & operator+= (const char *s)
opp_string & operator+= (const opp_string &s)
opp_string & operator+= (const std::string &s)
opp_string operator+ (const char *s)
opp_string operator+ (const opp_string &s)
opp_string operator+ (const std::string &s)
Constructor & Destructor Documentation
opp_string::opp_string () [inline]
Constructor.
opp_string::opp_string (const char * s) [inline]
Constructor.
References opp_strdup().
opp_string::opp_string (const char * s, int n) [inline]
Constructor.
opp_string::opp_string (const std::string & s) [inline]
Constructor.
References opp_strdup().
opp_string::opp_string (const opp_string & s) [inline]
Copy constructor.
References opp_strdup(), and str.
opp_string::~opp_string () [inline]
Destructor.
Member Function Documentation
const char* opp_string::c_str () const [inline]
Return pointer to the string.
Referenced by operator+().
bool opp_string::empty () const [inline]
Null (empty) string or not.
char* opp_string::buffer () [inline]
Returns pointer to the internal buffer where the string is stored.
It is allowed to write into the string via this pointer, but the length of the string should not be exceeded.
char* opp_string::reserve (unsigned size) [inline]
Allocates a buffer of the given size.
const char* opp_string::operator= (const char * s) [inline]
Deletes the old value and opp_strdup()'s the new value to create the object's own copy.
References opp_strdup().
opp_string& opp_string::operator= (const opp_string & s) [inline]
Assignment.
References str.
opp_string& opp_string::operator= (const std::string & s) [inline]
Assignment.
bool opp_string::operator< (const opp_string & s) const [inline]
Comparison.
References opp_strcmp(), and str.
opp_string& opp_string::operator+= (const char * s) [inline]
Concatenation.
opp_string& opp_string::operator+= (const opp_string & s) [inline]
Concatenation.
References str.
opp_string& opp_string::operator+= (const std::string & s) [inline]
Concatenation.
opp_string opp_string::operator+ (const char * s) [inline]
Concatenation.
opp_string opp_string::operator+ (const opp_string & s) [inline]
Concatenation.
References c_str().
opp_string opp_string::operator+ (const std::string & s) [inline]
Concatenation.
The documentation for this class was generated from the following file:
opp_string.h