OMNeT++ Simulation Library: cStatistic Class Reference
cStatistic Class Reference
[Statistical data collection]
#include <cstatistic.h>
Detailed Description
Base class of different statistic collecting classes.
cStatistic is the base class for all statistical data collection classes. cStatistic itself adds no data members or algorithms to cOwnedObject, it only defines virtual functions that will be redefined in descendants. No instance of cStatistic can be created.
Public Member Functions
Constructors, destructor, assignment.
cStatistic (const cStatistic &r)
cStatistic (const char *name=NULL)
virtual ~cStatistic ()
cStatistic & operator= (const cStatistic &res)
Redefined cObject member functions.
virtual void parsimPack (cCommBuffer *buffer)
virtual void parsimUnpack (cCommBuffer *buffer)
Collecting values.
virtual void collect (double value)=0
virtual void collect (SimTime value)
virtual bool isWeighted () const =0
virtual void collect2 (double value, double weight)
virtual void merge (const cStatistic *other)=0
virtual void clearResult ()=0
Statistics of collected data.
virtual long getCount () const =0
virtual double getSum () const =0
virtual double getSqrSum () const =0
virtual double getMin () const =0
virtual double getMax () const =0
virtual double getMean () const =0
virtual double getStddev () const =0
virtual double getVariance () const =0
Weighted statistics.
virtual double getWeights () const =0
virtual double getWeightedSum () const =0
virtual double getSqrSumWeights () const =0
virtual double getWeightedSqrSum () const =0
Transient and result accuracy detection.
void addTransientDetection (cTransientDetection *object)
void addAccuracyDetection (cAccuracyDetection *object)
cTransientDetection * getTransientDetectionObject () const
cAccuracyDetection * getAccuracyDetectionObject () const
Generating random numbers based on the collected data
void setGenK (int gen_nr)
virtual double random () const =0
Writing to text file, reading from text file, recording to scalar file.
virtual void saveToFile (FILE *) const =0
virtual void loadFromFile (FILE *)=0
virtual void record ()
virtual void recordWithUnit (const char *unit)
virtual void recordAs (const char *name, const char *unit=NULL)
Constructor & Destructor Documentation
cStatistic::cStatistic (const cStatistic & r)
Copy constructor.
cStatistic::cStatistic (const char * name = NULL) [explicit]
Constructor, creates an object with the given name.
virtual cStatistic::~cStatistic () [virtual]
Destructor.
Member Function Documentation
cStatistic& cStatistic::operator= (const cStatistic & res)
Assignment operator.
It is present since descendants may refer to it. The name member is not copied; see cNamedObject's operator=() for more details.
virtual void cStatistic::parsimPack (cCommBuffer * buffer) [virtual]
Serializes the object into an MPI send buffer.
Used by the simulation kernel for parallel execution. See cObject for more details.
Reimplemented from cOwnedObject.
Reimplemented in cDensityEstBase, cHistogramBase, cHistogram, cKSplit, cPSquare, cStdDev, cWeightedStdDev, and cVarHistogram.
virtual void cStatistic::parsimUnpack (cCommBuffer * buffer) [virtual]
Deserializes the object from an MPI receive buffer Used by the simulation kernel for parallel execution.
See cObject for more details.
Reimplemented from cOwnedObject.
Reimplemented in cDensityEstBase, cHistogramBase, cHistogram, cKSplit, cPSquare, cStdDev, cWeightedStdDev, and cVarHistogram.
virtual void cStatistic::collect (double value) [pure virtual]
Collects one value.
Implemented in cDensityEstBase, cLongHistogram, cStdDev, and cWeightedStdDev.
Referenced by cStdDev::collect().
virtual void cStatistic::collect (SimTime value) [inline, virtual]
Convenience method, delegates to collect(double).
Reimplemented in cDensityEstBase, cLongHistogram, cStdDev, and cWeightedStdDev.
References SimTime::dbl().
virtual bool cStatistic::isWeighted () const [pure virtual]
Returns true if this object collects weighted statistics.
Implemented in cStdDev, and cWeightedStdDev.
virtual void cStatistic::collect2 (double value, double weight) [virtual]
Collects one value with a given weight.
Reimplemented in cWeightedStdDev.
Referenced by cWeightedStdDev::collect(), and cWeightedStdDev::collect2().
virtual void cStatistic::merge (const cStatistic * other) [pure virtual]
Updates this object with data coming from another statistics object.
The result is as if this object had collected all the observations fed into the other object as well.
Implemented in cDensityEstBase, cKSplit, cPSquare, cStdDev, and cWeightedStdDev.
virtual void cStatistic::clearResult () [pure virtual]
This function should be redefined in derived classes to clear the results collected so far.
Implemented in cDensityEstBase, cHistogramBase, cStdDev, cWeightedStdDev, and cVarHistogram.
virtual long cStatistic::getCount () const [pure virtual]
Returns the number of the observations.
Implemented in cStdDev.
Referenced by cStdDev::getSqrSumWeights(), and cStdDev::getWeights().
virtual double cStatistic::getSum () const [pure virtual]
Returns the sum of the values.
See also:
getWeightedSum()
Implemented in cStdDev.
Referenced by cStdDev::getWeightedSum().
virtual double cStatistic::getSqrSum () const [pure virtual]
Returns the sum of the squared values.
See also:
getWeightedSqrSum()
Implemented in cStdDev.
Referenced by cStdDev::getWeightedSqrSum().
virtual double cStatistic::getMin () const [pure virtual]
Returns the minimum of the values.
Implemented in cStdDev.
virtual double cStatistic::getMax () const [pure virtual]
Returns the maximum of the values.
Implemented in cStdDev.
virtual double cStatistic::getMean () const [pure virtual]
Returns the mean of the (weighted) observations.
Implemented in cStdDev, and cWeightedStdDev.
virtual double cStatistic::getStddev () const [pure virtual]
Returns the standard deviation of the (weighted) observations.
Implemented in cStdDev.
virtual double cStatistic::getVariance () const [pure virtual]
Returns the variance of the (weighted) observations.
Implemented in cStdDev, and cWeightedStdDev.
virtual double cStatistic::getWeights () const [pure virtual]
Returns the sum of weights.
Implemented in cStdDev, and cWeightedStdDev.
virtual double cStatistic::getWeightedSum () const [pure virtual]
Returns the sum of weight*value products.
Implemented in cStdDev, and cWeightedStdDev.
virtual double cStatistic::getSqrSumWeights () const [pure virtual]
Returns the sum of squared weights.
Implemented in cStdDev, and cWeightedStdDev.
virtual double cStatistic::getWeightedSqrSum () const [pure virtual]
Returns the sum of weight*value*value products.
Implemented in cStdDev, and cWeightedStdDev.
void cStatistic::addTransientDetection (cTransientDetection * object)
Assigns transient and accuracy detection objects to the statistic object.
void cStatistic::addAccuracyDetection (cAccuracyDetection * object)
Assigns transient and accuracy detection objects to the statistic object.
cTransientDetection* cStatistic::getTransientDetectionObject () const [inline]
Returns the assigned transient and accuracy detection objects.
cAccuracyDetection* cStatistic::getAccuracyDetectionObject () const [inline]
Returns the assigned transient and accuracy detection objects.
void cStatistic::setGenK (int gen_nr) [inline]
Sets the index of the random number generator to use when the object has to generate a random number based on the statistics stored.
virtual double cStatistic::random () const [pure virtual]
Generates a random number based on the collected data.
Uses the random number generator set by setGenK(). This method is pure virtual, implementation is provided in subclasses.
Implemented in cHistogram, cKSplit, cPSquare, cStdDev, and cVarHistogram.
virtual void cStatistic::saveToFile (FILE *) const [pure virtual]
Writes the contents of the object into a text file.
This method is pure virtual, implementation is provided in subclasses.
Implemented in cDensityEstBase, cHistogramBase, cHistogram, cKSplit, cPSquare, cStdDev, cWeightedStdDev, and cVarHistogram.
virtual void cStatistic::loadFromFile (FILE *) [pure virtual]
Reads the object data from a file written out by saveToFile().
This method is pure virtual, implementation is provided in subclasses.
Implemented in cDensityEstBase, cHistogramBase, cHistogram, cKSplit, cPSquare, cStdDev, cWeightedStdDev, and cVarHistogram.
virtual void cStatistic::record () [inline, virtual]
Records the statistics into the scalar result file.
(Recorded data includes the number of observations, mean, standard deviation, min, max, potential histogram data, etc.) The name of the recorded statistic will be the object name (see getFullName()).
Note that this operation may have side effect: if this object is a histogram, the method may invoke the transform() on the histogram object, to force it set up histogram cells before recording.
virtual void cStatistic::recordWithUnit (const char * unit) [inline, virtual]
Records the statistics into the scalar result file, with the given unit (e.g.
"s", "m/s", etc). The name of the recorded statistic will be the object name (see getName()).
Note that this operation may have side effect: if this object is a histogram, the method may invoke the transform() on the histogram object, to force it set up histogram cells before recording.
virtual void cStatistic::recordAs (const char * name, const char * unit = NULL) [virtual]
Records the statistics into the scalar result file, with the given name, and optionally, the given unit (e.g.
"s", "m/s", etc).
Note that this operation may have side effect: if this object is a histogram, the method may invoke the transform() on the histogram object, to force it set up histogram cells before recording.
The documentation for this class was generated from the following file:
cstatistic.h