OMNeT++ Simulation Library: Random number generation
Random number generation
[Random number generation]
Functions
long intrand (long r)
double dblrand ()
long genk_intrand (int k, long r)
double genk_dblrand (int k)
Function Documentation
double dblrand () [inline]
Produces a random double in the range [0,1) using generator 0.
References cRNG::doubleRand().
double genk_dblrand (int k) [inline]
Produces a random double in the range [0,1) using generator k.
References cRNG::doubleRand().
Referenced by bernoulli().
long genk_intrand (int k, long r) [inline]
Produces a random integer in the range [0,r) using generator k.
References cRNG::intRand().
long intrand (long r) [inline]
Produces a random integer in the range [0,r) using generator 0.
References cRNG::intRand().