Tictoc Tutorial: Txc14 Class Reference
Txc14 Class Reference
Protected Member Functions
virtual TicTocMsg14 * generateMessage ()
virtual void forwardMessage (TicTocMsg14 *msg)
virtual void updateDisplay ()
virtual void initialize ()
virtual void handleMessage (cMessage *msg)
Private Attributes
long numSent
long numReceived
Detailed Description
In this step we keep track of how many messages we send and received, and display it above the icon.
Member Function Documentation
TicTocMsg14 * Txc14::generateMessage () [protected, virtual]
Referenced by handleMessage(), and initialize().
{
    // Produce source and destination addresses.
    int src = getIndex();   // our module index
    int n = size();      // module vector size
    int dest = intuniform(0,n-2);
    if (dest>=src) dest++;
    char msgname[20];
    sprintf(msgname, "tic-%d-to-%d", src, dest);
    // Create message object and set source and destination field.
    TicTocMsg14 *msg = new TicTocMsg14(msgname);
    msg->setSource(src);
    msg->setDestination(dest);
    return msg;
}
void Txc14::forwardMessage (TicTocMsg14 * msg) [protected, virtual]
Referenced by handleMessage().
{
    // Increment hop count.
    msg->setHopCount(msg->getHopCount()+1);
    // Same routing as before: random gate.
    int n = gateSize("gate");
    int k = intuniform(0,n-1);
    EV << "Forwarding message " << msg << " on gate[" << k << "]\n";
    send(msg, "gate$o", k);
}
void Txc14::updateDisplay () [protected, virtual]
Referenced by handleMessage().
{
    char buf[40];
    sprintf(buf, "rcvd: %ld sent: %ld", numReceived, numSent);
    getDisplayString().setTagArg("t",0,buf);
}
void Txc14::initialize () [protected, virtual]
Reimplemented from cComponent.
{
    // Initialize variables
    numSent = 0;
    numReceived = 0;
    WATCH(numSent);
    WATCH(numReceived);
    // Module 0 sends the first message
    if (getIndex()==0)
    {
        // Boot the process scheduling the initial message as a self-message.
        TicTocMsg14 *msg = generateMessage();
        scheduleAt(0.0, msg);
    }
}
void Txc14::handleMessage (cMessage * msg) [protected, virtual]
Reimplemented from cSimpleModule.
{
    TicTocMsg14 *ttmsg = check_and_cast<TicTocMsg14 *>(msg);
    if (ttmsg->getDestination()==getIndex())
    {
        // Message arrived
        int hopcount = ttmsg->getHopCount();
        EV << "Message " << ttmsg << " arrived after " << hopcount << " hops.\n";
        numReceived++;
        delete ttmsg;
        bubble("ARRIVED, starting new one!");
        // Generate another one.
        EV << "Generating another message: ";
        TicTocMsg14 *newmsg = generateMessage();
        EV << newmsg << endl;
        forwardMessage(newmsg);
        numSent++;
        if (ev.isGUI())
            updateDisplay();
    }
    else
    {
        // We need to forward the message.
        forwardMessage(ttmsg);
    }
}
Member Data Documentation
long Txc14::numSent [private]
Referenced by handleMessage(), initialize(), and updateDisplay().
long Txc14::numReceived [private]
Referenced by handleMessage(), initialize(), and updateDisplay().
The documentation for this class was generated from the following file:
txc14.cc