Tictoc Tutorial: Txc13 Class Reference
Txc13 Class Reference
Protected Member Functions
virtual TicTocMsg13 * generateMessage ()
virtual void forwardMessage (TicTocMsg13 *msg)
virtual void initialize ()
virtual void handleMessage (cMessage *msg)
Detailed Description
In this step the destination address is no longer node 2 -- we draw a random destination, and we'll add the destination address to the message.
The best way is to subclass cMessage and add destination as a data member. Hand-coding the message class is usually tiresome because it contains a lot of boilerplate code, so we let OMNeT++ generate the class for us. The message class specification is in tictoc13.msg -- tictoc13_m.h and .cc will be generated from this file automatically.
To make the model execute longer, after a message arrives to its destination the destination node will generate another message with a random destination address, and so forth.
Member Function Documentation
TicTocMsg13 * Txc13::generateMessage () [protected, virtual]
Referenced by handleMessage(), and initialize().
{
    // Produce source and destination addresses.
    int src = getIndex();   // our module index
    int n = size();      // module vector size
    int dest = intuniform(0,n-2);
    if (dest>=src) dest++;
    char msgname[20];
    sprintf(msgname, "tic-%d-to-%d", src, dest);
    // Create message object and set source and destination field.
    TicTocMsg13 *msg = new TicTocMsg13(msgname);
    msg->setSource(src);
    msg->setDestination(dest);
    return msg;
}
void Txc13::forwardMessage (TicTocMsg13 * msg) [protected, virtual]
Referenced by handleMessage().
{
    // Increment hop count.
    msg->setHopCount(msg->getHopCount()+1);
    // Same routing as before: random gate.
    int n = gateSize("gate");
    int k = intuniform(0,n-1);
    EV << "Forwarding message " << msg << " on gate[" << k << "]\n";
    send(msg, "gate$o", k);
}
void Txc13::initialize () [protected, virtual]
Reimplemented from cComponent.
{
    // Module 0 sends the first message
    if (getIndex()==0)
    {
        // Boot the process scheduling the initial message as a self-message.
        TicTocMsg13 *msg = generateMessage();
        scheduleAt(0.0, msg);
    }
}
void Txc13::handleMessage (cMessage * msg) [protected, virtual]
Reimplemented from cSimpleModule.
{
    TicTocMsg13 *ttmsg = check_and_cast<TicTocMsg13 *>(msg);
    if (ttmsg->getDestination()==getIndex())
    {
        // Message arrived.
        EV << "Message " << ttmsg << " arrived after " << ttmsg->getHopCount() << " hops.\n";
        bubble("ARRIVED, starting new one!");
        delete ttmsg;
        // Generate another one.
        EV << "Generating another message: ";
        TicTocMsg13 *newmsg = generateMessage();
        EV << newmsg << endl;
        forwardMessage(newmsg);
    }
    else
    {
        // We need to forward the message.
        forwardMessage(ttmsg);
    }
}
The documentation for this class was generated from the following file:
txc13.cc